Tall and skinny matrix $A$, unknown short vector $x$, long vector $y$.

Too many equations, not enough unknowns -- overdetermined.
Solve $Ax \approx y$.

Column space of $A$ (all combinations of columns of $A$) living in a hyperplane in a high-dimensional space: the space of all possible $Ax$s. The vector $y$ doesn't live in that space; project onto the column space.

In Julia, just type `A \ x` and it does all the work for you, giving the least-squares solution.

**Applications**:

Linear least squares (linear algebra is overkill):

Given $\{(x_i, y_i)\}$, find the best-fit line.

$$A = \begin{pmatrix} 1 & x_1 \\ 1 & x_2 \\ \vdots & \vdots \\ 1 & xn \end{pmatrix} 
\begin{pmatrix} y_intercept \\ slope \end{pmatrix} = \begin{pmatrix} y_1 \\ \vdots \\ y_n \end{pmatrix} $$

$$A^T A x = A^T y$$

so $$x = (A^T A)^{-1} A^T y$$

This is mathematically correct, but not how to actually compute.

Rather, take $A = QR$ and $x = R^{-1} Q^T y$

In this case, $A^T A = \begin{pmatrix} n & \sum x_i \\ \sum x_i & \sum_i x_i^2 \end{pmatrix}$

For nonlinear least squares, $A = \begin{pmatrix} 1 & x_1 & x_1^2 \\ ... \\ 1 & x_n & x_n^2 \end{pmatrix}$

Or e.g. fit to $c_1 e^x + c_2 \sin 3x + c_3 erf(x)$

## Example

In [2]:
xx = -3:0.1:3
yy = sin.(xx)

61-element Array{Float64,1}:
 -0.14112 
 -0.239249
 -0.334988
 -0.42738 
 -0.515501
 -0.598472
 -0.675463
 -0.745705
 -0.808496
 -0.863209
 -0.909297
 -0.9463  
 -0.973848
  ⋮       
  0.9463  
  0.909297
  0.863209
  0.808496
  0.745705
  0.675463
  0.598472
  0.515501
  0.42738 
  0.334988
  0.239249
  0.14112 

In [7]:
fs = [x -> x^i for i in 0:2]

M = [f(x) for f in fs, x in xx]'

61×3 Array{Float64,2}:
 1.0  -3.0  9.0 
 1.0  -2.9  8.41
 1.0  -2.8  7.84
 1.0  -2.7  7.29
 1.0  -2.6  6.76
 1.0  -2.5  6.25
 1.0  -2.4  5.76
 1.0  -2.3  5.29
 1.0  -2.2  4.84
 1.0  -2.1  4.41
 1.0  -2.0  4.0 
 1.0  -1.9  3.61
 1.0  -1.8  3.24
 ⋮              
 1.0   1.9  3.61
 1.0   2.0  4.0 
 1.0   2.1  4.41
 1.0   2.2  4.84
 1.0   2.3  5.29
 1.0   2.4  5.76
 1.0   2.5  6.25
 1.0   2.6  6.76
 1.0   2.7  7.29
 1.0   2.8  7.84
 1.0   2.9  8.41
 1.0   3.0  9.0 

In [9]:
M \ yy

3-element Array{Float64,1}:
  6.39816e-17
  0.331032   
 -1.57434e-17

In [2]:
using Plots, Interact

In [3]:
import Base: +, *

+(f::Function, g::Function) = x -> f(x) + g(x)
*(α::Number, f::Function) = x -> α*f(x)

* (generic function with 174 methods)

In [4]:
g = sin + 2cos
g(3) == sin(3) + 2cos(3)

true

In [5]:
ff(x) = 1 / (1 + 25x^2)
xx = -1:0.1:1
yy = ff.(xx);

xs = -1:0.001:1


-1.0:0.001:1.0

In [1]:
@manipulate for d in 1:20
    
    fs = [x -> x^i for i in 0:d]
    
    # fs = [exp, x->log(abs(x)), x->tan(2x)]

    M = [f(x) for f in fs[1:d], x in xx]'
    
    coeffs = M \ yy
    
    f = sum(coeffs[i] * fs[i] for i in 1:d)

        plot(xs, ff.(xs))
        plot!(xs, f.(xs))
        scatter!(xx, zeros(xx))
end

LoadError: LoadError: UndefVarError: @manipulate not defined
while loading In[1], in expression starting on line 1

In [13]:
xs

LoadError: LoadError: UndefVarError: xs not defined
while loading In[13], in expression starting on line 1